services:
  - type: web
    name: hackbook-web
    env: ruby
    region: oregon
    plan: free # or starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RUBY_VERSION
        value: 3.3.0
