databases:
  - name: hackbook-db
    databaseName: hackbook
    user: hackbook
    plan: free # or starter
    region: frankfurt # or wherever

services:
  - type: web
    name: hackbook-web
    env: ruby
    region: frankfurt
    plan: free # or starter
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hackbook-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RUBY_VERSION
        value: 3.3.0
