test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

supabase:
  service: S3
  access_key_id: <%= ENV["SUPABASE_S3_ACCESS_KEY"] %>
  secret_access_key: <%= ENV["SUPABASE_S3_SECRET_KEY"] %>
  region: <%= ENV.fetch("SUPABASE_REGION", "eu-central-1") %>
  bucket: <%= ENV.fetch("SUPABASE_BUCKET", "hackbook-uploads") %>
  endpoint: <%= ENV["SUPABASE_S3_ENDPOINT"] %>
  force_path_style: true

r2:
  service: S3
  access_key_id: <%= ENV["R2_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["R2_SECRET_ACCESS_KEY"] %>
  region: auto
  bucket: <%= ENV["R2_BUCKET"] %>
  endpoint: <%= ENV["R2_ENDPOINT"] %>
  force_path_style: true
